engines:
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseParameterName:
        enabled: false
languages:
  JavaScript: true
  PHP: true
exclude_paths:
- tests/**/*
- demo/**/*
- js/*.min.js
- js/jqueryui/**/*
- js/select2/**/*
